package view;

import java.util.List;
import java.util.ArrayList;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import model.Alimento;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import model.PedidoItem;
import javax.swing.JOptionPane;



public class TelaPedido extends javax.swing.JFrame {

    
    private DefaultTableModel modeloItens;
    private double totalPedido = 0.0;
    private java.util.List<PedidoItem> itensPedido;
    private static int proximoId = 1;
    private int idPedido;

    
    public TelaPedido() {
        initComponents();
        itensPedido = new java.util.ArrayList<>();
        idPedido = proximoId++;                       
 
        configurarTabela();    
        configurarSpinner();    
        atualizarTotal(); 
        preencherDataAtual();
    }
    
    public TelaPedido(java.util.List<PedidoItem> itensSelecionados) {
        this(); 
        adicionarItensSelecionados(itensSelecionados);
    }

    
    private void configurarTabela() {
        modeloItens = new DefaultTableModel(
            new Object[]{"Alimento", "Quantidade", "Preço Unitário", "Subtotal"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblItens.setModel(modeloItens);
    }

    private void configurarSpinner() {
        spQuantidade.setModel(new SpinnerNumberModel(1, 1, 100, 1));
    }


    private void atualizarTotal() {
        String texto = String.format("%.2f", totalPedido).replace('.', ',');
        txtTotalPedido.setText("R$ " + texto);
    }
    
    private void preencherDataAtual() {
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        String agora = LocalDateTime.now().format(fmt);
        txtDataPedido.setText(agora);
    }
    
    private void adicionarItensSelecionados(java.util.List<PedidoItem> itensSelecionados) {
    itensPedido.clear();
    itensPedido.addAll(itensSelecionados);

    modeloItens.setRowCount(0);
    totalPedido = 0.0;

    for (PedidoItem item : itensPedido) {

        String nome = item.getAlimento().getNome();
        int qtd = item.getQuantidade();
        double precoUnit = item.getPrecoUnitario();
        double subtotal = item.getSubtotal();

        String precoFormatado = "R$ " +
                String.format("%.2f", precoUnit).replace('.', ',');
        String subtotalFormatado = "R$ " +
                String.format("%.2f", subtotal).replace('.', ',');

        modeloItens.addRow(new Object[]{
            nome,
            qtd,
            precoFormatado,
            subtotalFormatado
        });

        totalPedido += subtotal;
    }

    atualizarTotal();
}
    
    private void recalcularTotal() {
    totalPedido = 0.0;
    for (PedidoItem item : itensPedido) {
        totalPedido += item.getSubtotal();
    }
    atualizarTotal();
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        pnlDadosPedido = new javax.swing.JPanel();
        txtDataPedido = new javax.swing.JTextField();
        lblDataPedido = new javax.swing.JLabel();
        txtTotalPedido = new javax.swing.JTextField();
        lblTotalPedido = new javax.swing.JLabel();
        pnlItensPedido = new javax.swing.JPanel();
        lblPreco = new javax.swing.JLabel();
        txtPrecoUnitario = new javax.swing.JTextField();
        lblQuantidade = new javax.swing.JLabel();
        spQuantidade = new javax.swing.JSpinner();
        btnAdicionarItem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItens = new javax.swing.JTable();
        btnRemoverItem = new javax.swing.JButton();
        btnRealizarPedido = new javax.swing.JButton();
        btnVoltarCardapio = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FeiFood - Pedido");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Detalhes do Pedido:");

        pnlDadosPedido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Do Pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        txtDataPedido.setEditable(false);
        txtDataPedido.setToolTipText("");

        lblDataPedido.setText("Data:");

        txtTotalPedido.setEditable(false);
        txtTotalPedido.setText("R$ 0,00");
        txtTotalPedido.setToolTipText("");

        lblTotalPedido.setText("Total:");

        javax.swing.GroupLayout pnlDadosPedidoLayout = new javax.swing.GroupLayout(pnlDadosPedido);
        pnlDadosPedido.setLayout(pnlDadosPedidoLayout);
        pnlDadosPedidoLayout.setHorizontalGroup(
            pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosPedidoLayout.createSequentialGroup()
                .addGroup(pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDataPedido)
                    .addComponent(txtTotalPedido)))
        );
        pnlDadosPedidoLayout.setVerticalGroup(
            pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosPedidoLayout.createSequentialGroup()
                .addGroup(pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataPedido)
                    .addComponent(txtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalPedido)
                    .addComponent(txtTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlItensPedido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Itens Do Pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        lblPreco.setText("Preço:");

        txtPrecoUnitario.setEditable(false);
        txtPrecoUnitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoUnitarioActionPerformed(evt);
            }
        });

        lblQuantidade.setText("Quantidade:");

        spQuantidade.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));
        spQuantidade.setToolTipText("");

        btnAdicionarItem.setText("Adicionar");
        btnAdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarItemActionPerformed(evt);
            }
        });

        tblItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblItens);

        javax.swing.GroupLayout pnlItensPedidoLayout = new javax.swing.GroupLayout(pnlItensPedido);
        pnlItensPedido.setLayout(pnlItensPedidoLayout);
        pnlItensPedidoLayout.setHorizontalGroup(
            pnlItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItensPedidoLayout.createSequentialGroup()
                .addGroup(pnlItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlItensPedidoLayout.createSequentialGroup()
                        .addComponent(lblPreco)
                        .addGap(37, 37, 37)
                        .addComponent(txtPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdicionarItem)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlItensPedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlItensPedidoLayout.setVerticalGroup(
            pnlItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItensPedidoLayout.createSequentialGroup()
                .addGroup(pnlItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreco)
                    .addComponent(txtPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantidade)
                    .addComponent(spQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRemoverItem.setText("Remover Item Selecionado");
        btnRemoverItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverItemActionPerformed(evt);
            }
        });

        btnRealizarPedido.setText("Realizar Pedido");
        btnRealizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarPedidoActionPerformed(evt);
            }
        });

        btnVoltarCardapio.setText("Voltar ao Cardápio");
        btnVoltarCardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarCardapioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRemoverItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVoltarCardapio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRealizarPedido)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlItensPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(pnlDadosPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDadosPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlItensPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoverItem)
                    .addComponent(btnVoltarCardapio)
                    .addComponent(btnRealizarPedido))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecoUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoUnitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoUnitarioActionPerformed

    private void btnAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarItemActionPerformed
         int linha = tblItens.getSelectedRow();

    if (linha == -1) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Selecione um item na tabela para alterar a quantidade.");
        return;
    }

    int novaQtd = (Integer) spQuantidade.getValue();

    PedidoItem item = itensPedido.get(linha);
    item.setQuantidade(novaQtd);

    double subtotal = item.getSubtotal();
    String subtotalFormatado = "R$ " +
            String.format("%.2f", subtotal).replace('.', ',');

    modeloItens.setValueAt(novaQtd, linha, 1);      
    modeloItens.setValueAt(subtotalFormatado, linha, 3); 

    recalcularTotal();
    }//GEN-LAST:event_btnAdicionarItemActionPerformed

    private void btnRemoverItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverItemActionPerformed
         int linha = tblItens.getSelectedRow();

    if (linha == -1) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Selecione um item para remover.");
        return;
    }

    itensPedido.remove(linha);          // tira da lista
    modeloItens.removeRow(linha);       // tira da tabela
    recalcularTotal();                  // atualiza o total                 
    }//GEN-LAST:event_btnRemoverItemActionPerformed

    private void btnRealizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarPedidoActionPerformed
        if (itensPedido == null || itensPedido.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Não há itens no pedido.");
        return;
    }

    JOptionPane.showMessageDialog(this,
            "Pedido " + idPedido + " realizado com sucesso!\n"
          + "Total: " + txtTotalPedido.getText());

    // 👉 AGORA VAI PARA A TELA DE AVALIAÇÃO
    TelaAvaliacao telaAval = new TelaAvaliacao(idPedido);
    telaAval.setLocationRelativeTo(this);
    telaAval.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_btnRealizarPedidoActionPerformed

    private void btnVoltarCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarCardapioActionPerformed
        Logado tela = new Logado();
    tela.setLocationRelativeTo(this);
    tela.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnVoltarCardapioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPedido().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarItem;
    private javax.swing.JButton btnRealizarPedido;
    private javax.swing.JButton btnRemoverItem;
    private javax.swing.JButton btnVoltarCardapio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDataPedido;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblTotalPedido;
    private javax.swing.JPanel pnlDadosPedido;
    private javax.swing.JPanel pnlItensPedido;
    private javax.swing.JSpinner spQuantidade;
    private javax.swing.JTable tblItens;
    private javax.swing.JTextField txtDataPedido;
    private javax.swing.JTextField txtPrecoUnitario;
    private javax.swing.JTextField txtTotalPedido;
    // End of variables declaration//GEN-END:variables
}
